# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# ID checks
# ID01: check that identifiers only use lowercase and hyphens
# ID02: check that identifiers have a minimum length
#
# Syntax checks
#
# Specify if syntax features are disabled. If the config is missing, it
# will considered as enabled.
#
# Example:
# SY01:
#     disabled: true
#
# SY01: terms
# SY02: message references
# SY03: term references
# SY04: variants
# SY05: attributes

---
ID01:
    enabled: false
    exclusions:
        messages: []
        files: []
ID02:
    enabled: false
    min_length: 6
    exclusions:
        messages: []
        files: []
CO01:
    enabled: true
    brands:
        - Firefox
        - Mozilla
        - Relay
        - Monitor
        - "{ -brand-mozilla } account"
    exclusions:
        messages:
            - breach-checklist-ssn-header
            - fxa-what-to-do-blurb-3
            - monitor-several-emails
            - rec-bank-acc-subhead
            - rec-cc-subhead
            - dashboard-top-banner-monitor-more-cta
            - announcement-add-up-to-20-emails-plus-title
        files: []
# Variable comments
VC:
    disabled: false
# Placeables style
PS01:
    disabled: false
