/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

export const dataBrokerNamesRecord: Record<string, string> = {
  "411locate.com": "411 Locate",
  "peoplefinders.com": "People Finders",
  "peoplesearchnow.com": "People Search Now",
  "privateeye.com": "Private Eye",
  "usa-people-search.com": "Usa People Search",
  "advancedbackgroundchecks.com": "Advanced Background Checks",
  "publicrecordsnow.com": "Public Records Now",
  "advanced-people-search.com": "Advanced People Search",
  "usphonebook.com": "US Phone Book",
  "golookup.com": "Go Lookup",
  "findpeoplesearch.com": "Find People Search",
  "fastpeoplesearch.com": "Fast People Search",
  "smartbackgroundchecks.com": "Smart Background Checks",
  "searchpeoplefree.com": "Search People Free",
  "cyberbackgroundchecks.com": "Cyber Background Checks",
  "usatrace.com": "Usa Trace",
  "quickpeopletrace.com": "Quickpeople Trace",
  "fastbackgroundcheck.com": "Fast Background Check",
  "cellrevealer.com": "Cell Revealer",
  "propeoplesearch.com": "Pro People Search",
  "callercenter.com": "Caller Center",
  "familytreenow.com": "Family Tree Now",
  "truepeoplesearch.com": "Truepeople Search",
  "instantcheckmate.com": "Instant Checkmate",
  "truthfinder.com": "Truth Finder",
  "ussearch.com": "Us Search",
  "zabasearch.com": "Zaba Search",
  "intelius.com": "Intelius",
  "addresses.com": "Addresses",
  "yellowpages.com": "Yellow Pages ",
  "onlinesearches.com": "Online Searches",
  "anywho.com": "AnyWho",
  "people.yellowpages.com": "The Real White Pages",
  "reversephonelookup.com": "Reverse Phone Lookup",
  "peoplesmart.com": "People Smart",
  "yellowbook.com": "YellowBook",
  "beenverified.com": "Been Verified",
  "open-public-records.com": "Open Public Records",
  "peoplelooker.com": "People Looker",
  "knowthycustomer.com": "Know Thy Customer",
  "searchsystems.net": "Search Systems",
  "neighborwho.com": "Neighbor Who",
  "numberguru.com": "Number Guru",
  "ownerly.com": "Ownerly",
  "bumper.com": "Bumper",
  "radaris.com": "Radaris",
  "pub360.com": "Pub360",
  "backgroundcheck.run": "Background Check",
  "newenglandfacts.com": "New England Facts",
  "veripages.com": "VeriPages",
  "people-background-check.com": "People Background Check",
  "centeda.com": "Centeda",
  "dataveria.com": "DataVeria",
  "verecor.com": "Verecor",
  "veriforia.com": "Veriforia",
  "councilon.com": "Councilon",
  "findrec.com": "FindRec",
  "vericora.com": "Vericora",
  "trustifo.com": "Trustifo",
  "inforver.com": "Inforver",
  "clubset.com": "Clubset",
  "wellnut.com": "Wellnut",
  "virtory.com": "Virtory",
  "kwold.com": "Kwold",
  "publicreports.com": "Public Reports",
  "neighbor.report": "Neighbor.Report",
  "clustrmaps.com": "ClustrMaps",
  "24counter.com": "24 Counter",
  "officialusa.com": "Official Usa",
  "recordsfinder.com": "Records Finder",
  "reversephonecheck.com": "Reverse Phone Check",
  "staterecords.org": "State Records",
  "idstrong.com": "Id Strong",
  "criminalpages.com": "Criminal Pages",
  "freebackgroundcheck.org": "Free Background Check",
  "searchquarry.com": "Searchquarry",
  "infotracer.com": "Info Tracer",
  "courtcasefinder.com": "Courtcase Finder",
  "affordablebackgroundchecks.com": "Affordable Background Checks",
  "texasarrestwarrants.org": "Texas Arrest Warrants",
  "texasarrests.org": "Texas Arrests",
  "verifythem.org": "Verify Them",
  "govwarrantsearch.org": "Gov Warrant Search",
  "texaswarrantroundup.org": "Texas Warrant Roundup",
  "usrecords.net": "Us Records",
  "uswarrants.org": "Us Warrants",
  "verifyarrestwarrant.com": "Verify Arrest Warrant",
  "rehold.com": "Rehold",
  "homemetry.com": "Homemetry",
  "whitepages.com": "White Pages",
  "411.com": "411",
  "peoplesearch.com": "People Search",
  "calltruth.com": "Call Truth",
  "nuwber.com": "Nuwber",
  "corporationwiki.com": "Corporation Wiki",
  "mylife.com": "MyLife",
  "addressbook.com": "AddressBook",
  "phonebooks.com": "Phone Books",
  "peekyou.com": "PeekYou",
  "spokeo.com": "Spokeo",
  "peoplewin.com": "People Win",
  "idtrue.com": "ID True",
  "freepeopledirectory.com": "Free People Directory",
  "persopo.com": "Persopo",
  "spyfly.com": "Spy Fly",
  "peoplebyname.com": "People By Name",
  "peoplesearchsite.com": "People Search Site",
  "thatsthem.com": "Thats Them",
  "checkpeople.com": "Check People",
  "backgroundalert.com": "Background Alert",
  "checkthem.com": "Check Them",
  "publicdatadigger.com": "Public Data Digger",
  "mashpanel.com": "Mash Panel",
  "cubib.com": "Cubib",
  "telephonedirectories.us": "Telephone Directories",
  "arivify.com": "Arivify",
  "yellowpagesdirectory.com": "Yellow Pages Directory",
  "socialcatfish.com": "Socialcatfish",
  "peoplewhiz.com": "People Whiz",
  "peoplewhiz.net": "People Whiz",
  "peoplewhizr.com": "People Whizr",
  "peoplewhizr.net": "People Whizr",
  "peoplewizard.net": "People Wizard",
  "peopleswhized.com": "People Swhized",
  "peopleswhizr.com": "People Swhizr",
  "peopleswiz.com": "People Swiz",
  "peopleswizard.com": "People Swizard",
  "peoplewhized.com": "People Whized",
  "peoplewhized.net": "People Whized",
  "peoplewiz.com": "People Wiz",
  "people-wizard.com": "People Wizard",
  "peoplewizr.com": "People Wizr",
  "tennhelp.com": "Tenn Help",
  "allpeople.com": "All People",
  "peoplebyphone.com": "People By Phone",
  "floridaresidentsdirectory.com": "Florida Residents Directory",
  "revealname.com": "Reveal Name",
  "ohioresidentdatabase.com": "Ohio Resident Database",
  "peoplesearchexpert.com": "People Search Expert",
  "hpcc-usa.org": "Hpcc Usa",
  "absolutepeoplesearch.com": "Absolute People Search",
  "privaterecords.net": "Private Records",
  "backgroundcheckers.net": "Background Checkers",
  "peoplesearcher.com": "People Searcher",
  "checksecrets.com": "Check Secrets",
  "peoplesearch123.com": "People Search123",
  "mugshotlook.com": "Mugshot Look",
  "inmatessearcher.com": "Inmates Searcher",
  "peoplesearchusa.org": "People Search Usa",
  "sealedrecords.net": "Sealed Records",
  "people-searchers.com": "People Searchers",
  "personsearchers.com": "Person Searchers",
  "privatereports.com": "Private Reports",
  "publicsearcher.com": "Public Searcher",
  "secretinfo.org": "Secret Info",
  "truthrecord.org": "Truth Record",
  "weinform.org": "We Inform",
  "allareacodes.com": "All Area Codes",
  "publicdatausa.com": "Public Data Usa",
  "locatepeople.org": "Locate People",
  "kidslivesafe.com": "Kids Live Safe",
  "arrestfacts.com": "Arrest Facts",
  "people-search.org": "People Search",
  "hodges-directory.us": "Hodges Directory",
  "privatenumberchecker.com": "Private Number Checker",
  "thisnumber.com": "This Number",
  "gladiknow.com": "Glad I Know",
  "americaphonebook.com": "America Phone Book",
  "unitedstatesphonebook.com": "United States Phone Book",
  "kiwisearches.com": "Kiwi Searches",
  "northcarolinaresidentdatabase.com": "Northcarolina Resident Database",
  "premium.telephonedirectories.us": "Premium Telephone Directories",
  "azerch.com": "Azerch",
  "topwa.org": "Topwa",
  "namesandfacts.com": "Names And Facts",
  "homedescription.com": "Home Description",
  "cocofinder.com": "Coco Finder",
  "clicksearch.us": "Click Search",
  "usapeopledata.com": "Usa People Data",
  "confidentialphonelookup.com": "Confidential Phone Lookup",
  "oldphonebook.com": "Old Phone Book",
  "homeownershipreport.com": "Homeownership Report",
  "publicdatacheck.com": "Public Data Check",
  "publicfinders.com": "Public Finders",
  "publicinfoservices.com": "Public Info Services",
  "searchpeopledirectory.com": "Search People Directory",
  "searchpublicrecords.com": "Search Public Records",
  "numberville.com": "Numberville",
  "411.info": "411.info",
};

export function getDataBrokerName(dataBrokerName: string) {
  return dataBrokerNamesRecord[dataBrokerName] ?? dataBrokerName;
}
