# Build app for integration tests
FROM node:14-slim

RUN useradd -d /app -u 1001 -g 1000 app

RUN npm update -g
RUN rm -rf /tmp/*

# RUN apk add --no-cache bash

WORKDIR /app

RUN chown app /app

USER app

COPY package.json package.json

RUN node -v
RUN npm install
RUN npm install wdio-image-comparison-service@2.3
RUN rm -rf ~app/.npm /tmp/*

COPY --chown=app:root . /app

RUN npm run build:all

CMD NODE_ICU_DATA=./node_modules/full-icu node server.js