export const breaches = data => `
<section>
  <h1>This is the breaches partial</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean egestas luctus magna in bibendum. Phasellus risus sapien, elementum eget ex eu, accumsan lobortis turpis. Donec eu arcu accumsan, tristique elit ac, accumsan nisl. Vestibulum sodales mollis lacus, commodo accumsan ipsum aliquam eget. Etiam efficitur vitae nisi et imperdiet. Nam finibus faucibus volutpat. Proin ultrices dui ac mauris dapibus iaculis. Aenean tincidunt, tortor sit amet iaculis rutrum, tellus erat condimentum dui, sed rhoncus nunc dolor ac sapien. Nulla dapibus consectetur mollis. Aenean sed tellus quis mauris pellentesque laoreet.</p>
  <p>Quisque finibus mollis risus, sit amet fringilla libero pharetra vel. Maecenas eget urna vehicula, dignissim orci sagittis, viverra lorem. Mauris nunc sapien, tristique vel faucibus eget, aliquam suscipit nibh. Sed porta pretium turpis, eget ornare sapien malesuada quis. Phasellus id tincidunt sapien. Curabitur in risus velit. Nullam ut ultrices elit, sit amet pulvinar odio. Sed fringilla sodales risus at interdum. Ut varius nunc sem, vitae vestibulum elit accumsan in. Ut tristique convallis leo sed commodo. Proin et dui eros. Nam lobortis ligula eu suscipit fermentum. Curabitur tincidunt sollicitudin ligula et posuere.</p>
  <p>Quisque ac euismod ante, non interdum felis. Nulla nec laoreet nisi. Curabitur fringilla dignissim cursus. Phasellus justo metus, ullamcorper et magna non, pellentesque aliquam quam. Integer enim turpis, auctor nec est quis, elementum rhoncus orci. Curabitur non feugiat nulla. Duis et ex vel orci malesuada iaculis. Sed lacus sem, aliquet id fermentum fermentum, feugiat vel mauris. Vivamus non pharetra odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus placerat maximus lacus, eget rhoncus risus iaculis sed.</p>
  <p>Curabitur dolor elit, interdum a massa quis, dignissim imperdiet ligula. Phasellus ut accumsan sem, eget porta nibh. In consectetur semper felis, eu accumsan ipsum gravida eu. Vivamus volutpat, ex quis varius interdum, nisl magna rutrum lectus, id scelerisque orci est non odio. Suspendisse rutrum nisi sed ante dignissim, ut congue ipsum commodo. Aliquam eleifend nisl id volutpat luctus. In hac habitasse platea dictumst. Quisque et tempor nunc, eu pulvinar nisi. Nam eget nunc vitae justo pulvinar consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
  <p>Curabitur et laoreet quam, sit amet pharetra elit. Proin nec finibus dolor. Fusce sollicitudin eu nibh sit amet mattis. Aenean consectetur, dolor eu euismod euismod, lorem odio mattis elit, et dapibus nunc libero ac leo. Duis fringilla purus sit amet lorem lobortis pulvinar. Proin id suscipit dui. Maecenas eleifend sem eu odio ultrices, sit amet maximus sem sollicitudin. Pellentesque id nunc ultricies ipsum tristique tristique. Nunc varius, sem eu lacinia sagittis, sem diam consequat sem, vel porttitor lacus est sit amet est. Duis sed lectus mollis, rhoncus nulla ut, ullamcorper massa. </p>
</section>
`
