/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import type { Meta, StoryObj } from "@storybook/react";

import { DataBrokerProfiles } from "../DataBrokerProfiles";
import { ScanResult } from "../../../functions/server/onerep";

// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
const meta: Meta<typeof DataBrokerProfiles> = {
  title: "DataBrokerProfiles",
  component: DataBrokerProfiles,
};
export default meta;
type Story = StoryObj<typeof DataBrokerProfiles>;

const MockScanResults = [
  {
    id: 9471,
    age: null,
    url: "https://api.onerep.com/scan-results/9471",
    link: "http://arivify.com/delectus-qui-autem-aut-eos-molestiae",
    emails: [
      "fabiola.roberts@hotmail.com",
      "tglover@padberg.org",
      "abby83@hotmail.com",
    ],
    phones: ["+6761131277838", "+7259948471722", "+5081093522301"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "27329-7294",
        city: "Oklahoma City",
        state: "OK",
        street: "Katrine Square",
      },
      {
        zip: "78914",
        city: "West Keeganchester",
        state: "HI",
        street: "Terry Trail",
      },
      {
        zip: "98816",
        city: "Schmittfort",
        state: "AK",
        street: "Tito Junctions",
      },
    ],
    last_name: "LastName",
    relatives: ["Nathanael Schowalter", "Julius Cummings", "Jesus Mraz"],
    created_at: "2023-07-20T15:18:18+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:18+0000",
    data_broker: "arivify.com",
    middle_name: "MiddleName",
    data_broker_id: 13,
  },
  {
    id: 9470,
    age: null,
    url: "https://api.onerep.com/scan-results/9470",
    link: "http://ussearch.com/pariatur-labore-doloribus-possimus-accusantium-est-sint",
    emails: [
      "ylind@hotmail.com",
      "ashtyn61@lemke.net",
      "timmothy23@konopelski.com",
    ],
    phones: ["+9927689570026", "+6280799775746", "+1928823893878"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "16176",
        city: "Oklahoma City",
        state: "OK",
        street: "Terry Springs",
      },
      {
        zip: "58089-9767",
        city: "Leannonton",
        state: "GA",
        street: "Goldner Ridges",
      },
      {
        zip: "99219-9640",
        city: "East Keithfort",
        state: "WV",
        street: "Laron Stream",
      },
    ],
    last_name: "LastName",
    relatives: ["Jed Medhurst", "Glennie Medhurst", "Waino White"],
    created_at: "2023-07-20T15:18:18+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:18+0000",
    data_broker: "ussearch.com",
    middle_name: "MiddleName",
    data_broker_id: 12,
  },
  {
    id: 9469,
    age: null,
    url: "https://api.onerep.com/scan-results/9469",
    link: "http://instantcheckmate.com/perferendis-dolores-tenetur-libero-ut-facilis",
    emails: [
      "ylind@hotmail.com",
      "ashtyn61@lemke.net",
      "timmothy23@konopelski.com",
    ],
    phones: ["+9927689570026", "+6280799775746", "+1928823893878"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "16176",
        city: "Oklahoma City",
        state: "OK",
        street: "Terry Springs",
      },
      {
        zip: "58089-9767",
        city: "Leannonton",
        state: "GA",
        street: "Goldner Ridges",
      },
      {
        zip: "99219-9640",
        city: "East Keithfort",
        state: "WV",
        street: "Laron Stream",
      },
    ],
    last_name: "LastName",
    relatives: ["Jed Medhurst", "Glennie Medhurst", "Waino White"],
    created_at: "2023-07-20T15:18:18+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:18+0000",
    data_broker: "instantcheckmate.com",
    middle_name: "MiddleName",
    data_broker_id: 11,
  },
  {
    id: 9468,
    age: null,
    url: "https://api.onerep.com/scan-results/9468",
    link: "http://truthfinder.com/magni-dolor-vel-accusamus-autem-qui-deserunt-rem",
    emails: [
      "ylind@hotmail.com",
      "ashtyn61@lemke.net",
      "timmothy23@konopelski.com",
    ],
    phones: ["+9927689570026", "+6280799775746", "+1928823893878"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "16176",
        city: "Oklahoma City",
        state: "OK",
        street: "Terry Springs",
      },
      {
        zip: "58089-9767",
        city: "Leannonton",
        state: "GA",
        street: "Goldner Ridges",
      },
      {
        zip: "99219-9640",
        city: "East Keithfort",
        state: "WV",
        street: "Laron Stream",
      },
    ],
    last_name: "LastName",
    relatives: ["Jed Medhurst", "Glennie Medhurst", "Waino White"],
    created_at: "2023-07-20T15:18:18+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:18+0000",
    data_broker: "truthfinder.com",
    middle_name: "MiddleName",
    data_broker_id: 10,
  },
  {
    id: 9467,
    age: null,
    url: "https://api.onerep.com/scan-results/9467",
    link: "http://smartbackgroundchecks.com/magni-qui-et-deserunt-est-sed-dicta-dignissimos",
    emails: [
      "earl39@deckow.com",
      "cassie53@breitenberg.biz",
      "bernita.davis@kovacek.com",
    ],
    phones: ["+9334231529749", "+7599982608197", "+7142134051613"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "49285",
        city: "Oklahoma City",
        state: "OK",
        street: "Liliana Centers",
      },
      {
        zip: "99625",
        city: "Port Josueview",
        state: "NH",
        street: "Steuber Meadow",
      },
      {
        zip: "63789-1958",
        city: "Port Nicolas",
        state: "MA",
        street: "Auer Villages",
      },
    ],
    last_name: "LastName",
    relatives: ["Anahi Effertz", "Emory Kling", "Trudie Prosacco"],
    created_at: "2023-07-20T15:18:17+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:17+0000",
    data_broker: "smartbackgroundchecks.com",
    middle_name: "MiddleName",
    data_broker_id: 6,
  },
  {
    id: 9466,
    age: null,
    url: "https://api.onerep.com/scan-results/9466",
    link: "http://privateeye.com/harum-sit-possimus-voluptatem-quia-perspiciatis",
    emails: [
      "earl39@deckow.com",
      "cassie53@breitenberg.biz",
      "bernita.davis@kovacek.com",
    ],
    phones: ["+9334231529749", "+7599982608197", "+7142134051613"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "49285",
        city: "Oklahoma City",
        state: "OK",
        street: "Liliana Centers",
      },
      {
        zip: "99625",
        city: "Port Josueview",
        state: "NH",
        street: "Steuber Meadow",
      },
      {
        zip: "63789-1958",
        city: "Port Nicolas",
        state: "MA",
        street: "Auer Villages",
      },
    ],
    last_name: "LastName",
    relatives: ["Anahi Effertz", "Emory Kling", "Trudie Prosacco"],
    created_at: "2023-07-20T15:18:17+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:17+0000",
    data_broker: "privateeye.com",
    middle_name: "MiddleName",
    data_broker_id: 5,
  },
  {
    id: 9465,
    age: null,
    url: "https://api.onerep.com/scan-results/9465",
    link: "http://peoplefinders.com/minima-aspernatur-repellendus-eum-voluptas",
    emails: [
      "earl39@deckow.com",
      "cassie53@breitenberg.biz",
      "bernita.davis@kovacek.com",
    ],
    phones: ["+9334231529749", "+7599982608197", "+7142134051613"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "49285",
        city: "Oklahoma City",
        state: "OK",
        street: "Liliana Centers",
      },
      {
        zip: "99625",
        city: "Port Josueview",
        state: "NH",
        street: "Steuber Meadow",
      },
      {
        zip: "63789-1958",
        city: "Port Nicolas",
        state: "MA",
        street: "Auer Villages",
      },
    ],
    last_name: "LastName",
    relatives: ["Anahi Effertz", "Emory Kling", "Trudie Prosacco"],
    created_at: "2023-07-20T15:18:17+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:17+0000",
    data_broker: "peoplefinders.com",
    middle_name: "MiddleName",
    data_broker_id: 4,
  },
  {
    id: 9464,
    age: null,
    url: "https://api.onerep.com/scan-results/9464",
    link: "http://open-public-records.com/id-aut-non-ducimus-reprehenderit",
    emails: [
      "arno.brakus@harris.com",
      "ogleichner@wisozk.com",
      "thompson.adolphus@davis.com",
    ],
    phones: ["+6404896443126", "+4919086248867", "+8723461177530"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "55064-7013",
        city: "Oklahoma City",
        state: "OK",
        street: "Jeramy Cove",
      },
      {
        zip: "92952",
        city: "Port Kris",
        state: "VA",
        street: "Clementine Isle",
      },
      {
        zip: "06495",
        city: "Elenoraview",
        state: "MO",
        street: "Vito Ways",
      },
    ],
    last_name: "LastName",
    relatives: ["Leonardo Bechtelar", "Jennie Skiles", "Ari Schuppe"],
    created_at: "2023-07-20T15:18:17+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:17+0000",
    data_broker: "open-public-records.com",
    middle_name: "MiddleName",
    data_broker_id: 3,
  },
  {
    id: 9463,
    age: null,
    url: "https://api.onerep.com/scan-results/9463",
    link: "http://peoplesmart.com/repudiandae-maiores-est-ducimus-consequuntur-neque",
    emails: [
      "arno.brakus@harris.com",
      "ogleichner@wisozk.com",
      "thompson.adolphus@davis.com",
    ],
    phones: ["+6404896443126", "+4919086248867", "+8723461177530"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "55064-7013",
        city: "Oklahoma City",
        state: "OK",
        street: "Jeramy Cove",
      },
      {
        zip: "92952",
        city: "Port Kris",
        state: "VA",
        street: "Clementine Isle",
      },
      {
        zip: "06495",
        city: "Elenoraview",
        state: "MO",
        street: "Vito Ways",
      },
    ],
    last_name: "LastName",
    relatives: ["Leonardo Bechtelar", "Jennie Skiles", "Ari Schuppe"],
    created_at: "2023-07-20T15:18:17+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:17+0000",
    data_broker: "peoplesmart.com",
    middle_name: "MiddleName",
    data_broker_id: 2,
  },
  {
    id: 9462,
    age: null,
    url: "https://api.onerep.com/scan-results/9462",
    link: "http://beenverified.com/atque-magni-debitis-eveniet-eius-fugiat-sed-blanditiis-et",
    emails: [
      "arno.brakus@harris.com",
      "ogleichner@wisozk.com",
      "thompson.adolphus@davis.com",
    ],
    phones: ["+6404896443126", "+4919086248867", "+8723461177530"],
    status: "new",
    scan_id: 1315,
    addresses: [
      {
        zip: "55064-7013",
        city: "Oklahoma City",
        state: "OK",
        street: "Jeramy Cove",
      },
      {
        zip: "92952",
        city: "Port Kris",
        state: "VA",
        street: "Clementine Isle",
      },
      {
        zip: "06495",
        city: "Elenoraview",
        state: "MO",
        street: "Vito Ways",
      },
    ],
    last_name: "LastName",
    relatives: ["Leonardo Bechtelar", "Jennie Skiles", "Ari Schuppe"],
    created_at: "2023-07-20T15:18:17+0000",
    first_name: "LastName",
    profile_id: 872,
    updated_at: "2023-07-20T15:18:17+0000",
    data_broker: "beenverified.com",
    middle_name: "MiddleName",
    data_broker_id: 1,
  },
] as ScanResult[];

export const DataBrokerProfilesItem: Story = {
  args: {
    data: MockScanResults,
  },
};
