name: Monitor Cron e2e Tests
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the e2e against'
        required: false
        default: 'stage'
        type: choice
        options:
          - stage
          - prod
          - heroku
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11

      - name: Install dependencies
        run: npm ci
      - name: Copy env var
        run: cp .env-dist .env
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup Playwright Browser
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright tests - ${{ inputs.environment != null && inputs.environment || 'stage' }}
        if: github.actor != 'dependabot[bot]'
        run: npm run e2e
        timeout-minutes: 20
        env:
          E2E_TEST_ENV: ${{ inputs.environment != null && inputs.environment || 'stage' }}
          E2E_TEST_BASE_URL: ${{ secrets.E2E_TEST_BASE_URL }}
          E2E_TEST_ACCOUNT_EMAIL: ${{ secrets.E2E_TEST_ACCOUNT_EMAIL }}
          E2E_TEST_ACCOUNT_PASSWORD: ${{ secrets.E2E_TEST_ACCOUNT_PASSWORD }}
          ADMINS: ${{ secrets.ADMINS }}
          FXA_ENABLED: true
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          ONEREP_API_KEY: ${{ secrets.ONEREP_API_KEY }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          HIBP_KANON_API_TOKEN: ${{ secrets.HIBP_KANON_API_TOKEN }}
          HIBP_API_TOKEN: ${{ secrets.HIBP_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: src/e2e/test-results/
          retention-days: 30
