name: Lint

permissions: {}

on:
  pull_request:
  push:

jobs:
  npm-lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '20.20.x'
      - run: npm ci
      - run: npm run build-glean
      - run: npm run build-nimbus
      # Mirror old linter from CircleCI, verifies that linter succeeds
      - run: npm run lint
      - run: node src/scripts/build/checkNodeVersionAlignment.js
      - run: node src/scripts/build/checkGithubActionsBestPractices.js
