name: ssdlc-sbom

permissions: {}

on:
  release:
    types: [published]
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  sbom:
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@9ecc28ba241cdaa0b207cc2c352c2faa954732f8
    with:
      sbom_name: ${{ github.event.release.tag_name || github.sha }}
    permissions:
      actions: read
      contents: write
