name: ssdlc-sbom

permissions: {}

on:
  release:
    types: [published]
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  sbom:
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@ca8be48f3c06204fb16a3bd5ffa6d916782bbc76
    with:
      sbom_name: ${{ github.event.release.tag_name || github.sha }}
    permissions:
      actions: read
      contents: write
